### ISSUE TITLE
Unable to transport ISIS, LDP and RSVP packets between PODs in diff k8 nodes - MESHNET

### ISSUE THREAD

**Issue by jdhandap** [openconfig/kne#282]
Hi Team

We are running KNE in a K8 cluster with 4 VMs(one controller and 3 workers). 

a) We are running into the following issue where we are unable to get ISIS, LDP and RSVP sessions up across PODS that are hosted on different VMs .

**Troubleshooting done:**
1. LLDP, BGP protocol sessions do come up across PODS hosted on **different** VMs.
2.  OTOH, these protocols (ISIS, LDP and RSVP ) do come up when the PODS are hosted on the **same** VM. 
3. Used Arista cEOS  and Cisco 8201 to test this behavior and same result.
4. Tried flipping between VXLAN and GRPC as the value for “INTER_NODE_LINK_TYPE” in the meshnet deamon and no luck.

**Comment by alexmasi** [comment]
I did make updates to the multinode guide (https://github.com/openconfig/kne/blob/main/docs/multinode.md) around the same time this issue was filed. The changes included updates to meshnet to support grpc-wires. I would confirm that you are using the most up to date version of meshnet grpc manifest found in this repo: https://github.com/openconfig/kne/blob/d1bdb669d3f3a7e73c7f000f3bb1b032588d64ca/deploy/kne/external-multinode.yaml#L16

Let me know if this fixes the issue or if you're already running with that setup

**Comment by jdhandap** [comment]
@alexmasi : Sorry, couldn’t respond earlier. Yes with the latest MESHNET, various layer 2 protocols (ISIS, LDP) does work. Thanks for the pointer and help.
